### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Peet1986** [TheComputerGenie/PirateOcean#7]
Maybe i am to nooby for installing the Wallet on my ElementaryOS (ubuntu), if do the step by step install instruction, all is fine, till the last step, when i have to enter ./build.sh. The Process is running till the Point, where the Wallet should start i think, but in Terminal only are the messages: 

configure: error: Could not link against boost_system-mt!
cp: Can not call stat for 'src / qt / komodo-qt': file or directory not found
rm: removing 'src / qt / komodo-qt' is not possible: file or directory not found
./build.sh: Line 10: ./PirateWallet: File or directory not found

**Comment by TheComputerGenie** [comment]
That's building, not "installing" and that version is no longer supported
